### ISSUE TITLE
[Bug] AttributeError: 'LanguageInfo' object has no attribute 'file'

### ISSUE THREAD

**Issue by billyeatcookies** [Dmunch04/pastemyst-py#2]
An attribute error is thrown when trying to fetch a LanguageInfo object
> ```py
> File "...\path\to\foo.py", line 57, in paste_message
>    pastemyst_language = client.get_language_info(ext=language)
>  File "...\venv\lib\site-packages\pastemyst\client.py", line 24, in get_language_info
>    lang.from_dict(raw)
>  File "...\venv\lib\site-packages\pastemyst\models\language.py", line 12, in from_dict
>    setattr(self, spacify_string(attr), data[attr])
>AttributeError: 'LanguageInfo' object has no attribute 'file'
> ```

**Comment by Dmunch04** [comment]
pr is merged
